DefaultLanguage = 'zh-Hans'
# UILoginBackgroundUrl = 'https://eoesonic.com:9443/s/DnGwnzAYKipQRx8/preview'
UILoginBackgroundUrl = 'http://124.220.153.22:30080/s/GEWmcFHKrQrGzJK/preview'
UIWelcomeMessage = '多想闭上眼，听你声音在耳边~'
EnableSharing = true
LastFM.Enabled = false
RecentlyAddedByModTime = true
